### ISSUE TITLE
gitupdate.sh file not included in release pacakge

### ISSUE THREAD

**Issue by aborn** [aborn/eeb#1]
23:41:25.896 [error] GenServer :githubwebhookserver terminating
*\* (stop) :enoent
    :erlang.open_port({:spawn_executable, '/home/aborn/eeb_aborn/scripts/gitupdate.sh'}, [:use_stdio, :exit_status, :binary, :hide, {:args, ["/home/aborn/github/technotebook"]}])
    (elixir) lib/system.ex:456: System.cmd/3
    (eeb) lib/eeb/github_webhook.ex:44: Eeb.GithubWebhook.handle_cast/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:update_blog}}

**Comment by aborn** [comment]
fixed in v0.2.0
